# Generated by Django 5.1.2 on 2024-10-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0003_rename_artículo_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='Articles'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='Categories'),
        ),
    ]
