# Generated by Django 5.1.2 on 2025-08-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_post', '0004_alter_article_image_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='User_id',
            new_name='author',
        ),
    ]
