# Generated by Django 5.1.2 on 2025-08-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_about_profile_birthday_profile_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='Profiles/default-user.png', null=True, upload_to='Profiles'),
        ),
    ]
